apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-http
  name: deployment-go-http
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-http
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-http
    spec:
      containers:
        - image: seanturner026/kube-playground-http-server
          imagePullPolicy: Always
          name: go-http
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
          env:
            - name: COLOR
              value: blue
          ports:
            - name: http
              containerPort: 3000
