---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: go-http
  name: ingress-go-http
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service-go-http
                port:
                  number: 80
